[pytest]
# Run tests in parallel (-n auto), generate HTML report, define base URL
addopts = --base-url https://www.saucedemo.com/ --headed
testpaths = tests
log_cli = true
log_cli_level = INFO
log_file_level = INFO
markers =
    ui: UI tests
    api: API tests
    db: Database tests
    e2e: End-to-end tests
